#!/usr/bin/env bash

cat > Dockerfile <<"EOF"
FROM ocaml/opam:ubuntu-22.04-opam AS base

RUN sudo apt-get update && sudo apt-get install -y gawk autoconf2.69
RUN sudo apt-get install -y vim

# Clone relocatable
RUN git clone https://github.com/dra27/relocatable.git

WORKDIR relocatable

RUN git submodule update --init ocaml

# Configure Git
WORKDIR ocaml
RUN git config --local user.name 'David Allsopp'
RUN git config --local user.email 'david.allsopp@metastack.com'
# Ensure the normal merge style is in effect or rerere doesn't appear to work!
RUN git config --local merge.conflictstyle merge
# Enable rerere with ~10 year retention of resolutions
RUN git config --local rerere.enabled true
RUN git config --local gc.rerereResolved 3650
# Speed up reconfiguration stage by sharing config.status
RUN git config --local ocaml.configure-cache ..
# Necessary for some of the more complicated rebasing
RUN git config --local merge.renameLimit 150000
# Check commits created by the script (disable the configure check)
RUN sed -e '/If any/iexit $STATUS' tools/pre-commit-githook > ../.git/modules/ocaml/hooks/pre-commit
RUN chmod +x ../.git/modules/ocaml/hooks/pre-commit
# Sync with upstream
RUN git remote add upstream https://github.com/ocaml/ocaml.git --fetch

EOF

for lock in $(git -C ocaml log --oneline --first-parent --format=%h --reverse origin/relocatable-locks | tail -n +2); do
  echo "FROM base AS lock-$lock"
  echo "RUN script --return --command '../stack $lock' ../log"
done >> Dockerfile

cat >> Dockerfile <<"EOF"

FROM base AS collect
WORKDIR /home/opam
EOF

for lock in $(git -C ocaml log --oneline --first-parent --format=%h --reverse origin/relocatable-locks | tail -n +2); do
  echo "COPY --from=lock-$lock /home/opam/relocatable/log lock-$lock"
done >> Dockerfile

cat >> Dockerfile <<"EOF"
COPY --chmod=755 <<EOF display.sh
#!/bin/sh

EOF

sed_line="'1,/^Backport summary/d;/^Script done on/d'"
for lock in $(git -C ocaml log --oneline --first-parent --format=%h --reverse origin/relocatable-locks | tail -n +2); do
  echo "echo \"Lock $lock: \$(git -C relocatable/ocaml log -1 --format=%s $lock)\""
  echo "sed -e $sed_line lock-$lock"
  sed_line="'1,/^ - Trees differ/d;/^Script done on/d'"
done >> Dockerfile

cat >> Dockerfile <<ZOF
EOF
ZOF
