#!/usr/bin/env bash

state_file="$(realpath $(dirname "$0"))/.stack-state"
lock_index="$(realpath $(dirname "$0"))/.lock-index"
dir="$(realpath $(dirname $0)/ocaml)"

if [[ ! -d $dir ]]; then
  echo "Expect OCaml clone in $dir" >&2
  exit 1
fi

cd "$dir"

if ! git rev-parse --verify upstream/trunk &> /dev/null; then
  echo 'Could not find upstream/trunk' >&2
  exit 1
fi

if ! git rev-parse --verify relocatable-locks &> /dev/null; then
  if ! git rev-parse --verify origin/relocatable-locks &> /dev/null; then
    echo "origin/relocatable-locks not found?!" >&2
    exit 1
  fi
  git branch --track relocatable-locks origin/relocatable-locks
fi

if [[ -n $1 ]]; then
  if [[ $1 = ${1#@} ]]; then
    if ! git rev-parse --verify "$1" &> /dev/null; then
      echo "Lock not found: $1" >&2
      exit 1
    fi

    lock="$(git rev-parse "$1")"
    contained="$(git branch relocatable-locks --contains "$lock")"
    if [[ -z $contained ]]; then
      echo "Lock not found: $1" >&2
      exit 1
    fi

    git --work-tree=../.git/modules/ocaml restore --source=$lock --worktree -- rr-cache
    backports="$lock"
    lock="git show $lock:branches"

    rm -f ../branches
  else
    lock="$(realpath ${1#@})"
    lock="cat \"$lock\""
    rm -f ../branches
    cp "${1#@}" ../branches
    backports=''
  fi
else
  lock=''
  backports=''
fi

start_time=$(date '+%Y-%m-%d %H:%M:%S')

declare -A HEADS

if [[ -z $lock ]]; then
  # fix-autogen appears first, since it affects any commit touching configure.
  # Part of #10254 allows overriding the autoconf command in autogen.
  # They don't need to go in branches, however.
  BRANCHES=(fix-autogen@4.08 check-configure@4.12)

  # Existing patches in maintenance branches and in opam-repository
  # - Compatibility with -fno-common default in GCC 10 (#9180; 4.09.1)
  #   opam-repository carries a different patch; passing -fcommon to configure
  BRANCHES+=(fcommon@4.08)
  # - SIGSTKSZ change in glibc 2.34 (#10266 and #10726; 4.13.0, 4.14.0)
  #   opam-repository carries this patch already
  BRANCHES+=(sigaltstack sigaltstack-4.09@fixup)
  # - Correct configure script for 4.09.1
  #   configure wasn't regenerated; opam-repository carries this patch already
  BRANCHES+=(fix-4.09.1-configure@4.09)

  # Existing patch in maintenance branch and proposed for opam-repository
  # - Fix installing tools links when bytecode programs disabled
  #     (#8858; 4.09.1, 4.10.0)
  #   Permits the disabling of bytecode tool installation on 4.08+
  BRANCHES+=(install-bytecode@4.08)

  # Existing patches in maintenance branches and proposed for opam-repository
  # - Allow the reconfigure target on Windows (#8996; 4.09.1, 4.10.0)
  #   **Critical**: graphics.4.08.0 and graphics.4.08.1 require it
  BRANCHES+=(win-reconfigure@4.08)
  # - Compatibility mingw-w64's ANSI stdio.h changes
  #     (#9939; 4.10.2, 4.11.2, 4.12.0)
  #   **Critical**: OCaml doesn't build with mingw-w64 headers 8.0.0+ otherwise
  BRANCHES+=(mingw-headers@4.09)

  # Proposed back-ports to opam-repository only
  # - SUBST_STRING macro in utils/Makefile (from #8650; 4.10.0)
  #   Dependency of #9285
  # - Link all DLLs with -static-libgcc on mingw32 (#9285 and #10046; 4.12.0)
  #   **Critical**: i686 mingw-w64 OCaml requires a runtime DLL not available by
  #                 default
  # - Update config.sub and config.guess (no PR; 4.12.0)
  BRANCHES+=(makefile-tweaks@4.09 static-libgcc@4.11 config.guess@4.11 config.guess-4.09@4.09)

  # Proposed back-ports to maintenance branches and opam-repository:
  # - Compatibility with binutils 2.36+ on mingw-w64 x64
  #     (#10351; 4.12.1, 4.13.0)
  #   **Critical**: fix in 4.12.1 is too high risk to back-port, this alters the
  #                 linker flags instead. mingw-w64 x64 is unusable without this
  BRANCHES+=(fix-binutils-2.36@4.11)
  # - Compatibility with mingw-w64 headers 8.0.0 (#10062; 4.12.0)
  #   **Critical**: both mingw-w64 ports require this tweak for the headers to
  #                 behave correctly if user-code loads <stdio.h> (or other
  #                 headers pulling in mingw.h) before <caml/config.h>
  BRANCHES+=(fix-mingw-lld@4.11)
  # - Fix parallel generation of header programs (#2267 + #8626; 4.09.0)
  #   Prerequisite for faster-flexdll on 4.08 (and also fixes Cygwin compilation
  #   on 4.08)
  BRANCHES+=(merge-headers@4.08)
  # - FlexDLL bootstrapping overhaul (#10135; 4.13.0)
  #   Vastly improves the build performance and reliability on Windows.
  #   Simplifies the packaging for ocaml-base-compiler.
  BRANCHES+=(faster-flexdll-4.12@4.12 faster-flexdll-4.11@4.11@fixup faster-flexdll-4.08@4.08@fixup)
  # - Add --disable-stdlib-manpages to configure (#8835 and #9335; 4.11.0)
  #   --disable-stdlib-manpages was added in 4.10.0 but broken by the time of
  #   release. The build is very time-consuming, especially on Windows, so this
  #   is recommended to allow the Windows configuration to use it
  BRANCHES+=(fix-stdlib-manpages-4.09@4.09 fix-stdlib-manpages@4.10)
  # - Add --disable-ocamltest to configure (#9250; 4.11.0)
  #   ocamltest is never installed, but the build uses time and resources.
  #   Propose back-porting this to save time on older compiler builds.
  BRANCHES+=(disable-ocamltest@4.10)

  # These all simplify the testing infrastructure, but aren't required:
  # - Add --enable-warn-error (from #9625; 4.12.0)
  # - Fix warn-error issues with win32graph (ocaml/graphics#28)
  # - Allow make's default target to build the compiler (from #8951; 4.10.0)
  # - Revert the Wdeclaration-after-statement dev-error
  #     (from #1176; 4.11.0 - back-ports part of #11051; 5.0.0)
  # - Don't define _INTEGRAL_MAX_BITS in Windows stat implementation
  #     (#9686; 4.12.0)
  # - autoconf tweaks (#8639; 4.11.0)
  # - fix tools/check-symbol-names (#9260; 4.11.0)
  BRANCHES+=(win32-safe-string@4.08 _integral_max_bits@4.11 declaration-after-statement@4.14 warn-error@4.11 make-default-target@4.09 autoconf-tweak@4.10 autoconf-tweak-4.09@fixup~1 runtime_name_escape@4.10)

  # - CI tweaks and backports
  BRANCHES+=(improve-depend-from-scratch@4.09 ocamltest 32bit-gha-test@5.0 github-attributes@4.11 ocamltest-4.14@4.14 ocamltest-4.12@4.12 ocamltest-4.11@4.11 ocamltest-tweak@4.11 ocamltest-4.09@fixup~2 fix-test-4229@4.09 ocamltest-4.08@4.08 faster-appveyor@4.10)

  # This slightly simplifies the patch rebasing infrastructure, as it stops
  # configure from being completely rejected
  # - Ensure that configure can be patched (#9847; 4.12.0)
  BRANCHES+=(no-configure@4.11)

  # Back-ports
  # NB These back-ports have been selected to ease the back-porting of the main
  # PRs. Some of the back-ports will want tweaking after the PRs are finalised.
  # For example, back-porting #1941 and #8992 makes the -set-global-string
  # portion of enable-relative rebase more easily, but the better back-port
  # would be to add the argument using the pre-4.10 mechanisms.
  # - Original long shebang "fix" (#8622; 4.10.0)
  # - Hardening of -use-runtime for spaces and symbols (#11112; 5.0.0)
  # - Expose Config.ext_exe (from #9652; 4.12.0)
  # - Caml_inline macro (from #1176; 4.11.0)
  # - _T / T macro (#2075; 4.09.0)
  # - ocamlrun -config (#9284; 4.13.0)
  # - Eliminate tools/ocamlmklibconfig.ml (#10204; 4.13.0)
  # - Add HAS_REALPATH to s.h (from #10047; 4.13.0)
  # - Add runtime/build_config.h (from #10451; 4.13.0)
  # - Simplification of ocamlcp/ocamloptp processing (#1941; 4.09.0)
  # - Share argument implementations (from #8992; 4.10.0)
  BRANCHES+=(ext_exe@4.11 shebang@4.09 c89_headers@4.10 rename_T_macro@4.08 use-runtime-evil@4.14 use-runtime-evil-fixup@fixup ocamlrun-config@4.12 ocamlmklibconfig-cleanup@4.12 unix-realpath@4.12 build_config@4.12 build_config-4.11@fixup build_config-4.08@fixup ocamlc-dedup3@4.08 shared_args-4.09@4.09 shared_args-4.08@4.08)

  # Branches
  #  - misc-win-fixes
  #  - windows-ln
  #  - one-camlheader
  BRANCHES+=(misc-win-fixes windows-ln windows-ln-5.0@fixup windows-ln-4.11@fixup one-camlheader one-camlheader-4.13@fixup~1)
  #  - target-bindir
  BRANCHES+=(target-bindir target-bindir-5.0@fixup)
  #  - ld.conf-CRLF
  #  - ld.conf-search
  BRANCHES+=(ld.conf-CRLF ld.conf-search)
  #  - ld.conf-relative
  BRANCHES+=(ld.conf-relative unified-ld.conf-relative@4.14)
  #  - compiled-primitives
  BRANCHES+=(compiled-primitives compiled-primitives-5.0@fixup compiled-primitives-4.12@fixup)
  #  - enable-relative
  BRANCHES+=(enable-relative unified-enable-relative@fixup~1 unified-enable-relative-5.0@fixup~1 unified-enable-relative-4.x@4.14@fixup unified-enable-relative-4.11@4.11@fixup cmmgen-4.09@fixup~1 unified-enable-relative-4.08@4.08@fixup)
  #  - ld-warning
  BRANCHES+=(ld-warning ld-warning-5.0@fixup)
  #  - runtime-id
  BRANCHES+=(runtime-id runtime-id-5.0@fixup runtime-id-4.14@fixup runtime-id-4.13@fixup runtime-id-4.12@fixup runtime-id-4.11@fixup runtime-id-4.10@fixup runtime-id-4.09@fixup runtime-id-4.08@fixup)
  #  - runtime-suffixing
  BRANCHES+=(runtime-suffixing unified-runtime-suffixing@trunk@fixup unified-runtime-suffixing-5.0@5.0@fixup unified-runtime-suffixing-4.14@4.14@fixup unified-runtime-suffixing-4.12@fixup unified-runtime-suffixing-4.11@fixup~1)
  #  - camlheader-search
  BRANCHES+=(camlheader-search unified-camlheader-search@fixup~1 unified-camlheader-search-5.0@fixup~1 unified-camlheader-search-4.14@fixup~1 unified-camlheader-search-4.13@fixup~1 unified-camlheader-search-4.12@fixup~1 unified-camlheader-search-4.11@fixup~1 unified-camlheader-search-4.10@fixup~1)

  TARGETS=(trunk 5.0 4.14 4.13 4.12 4.11 4.10 4.09 4.08)

  # Check the branches all exist and collect the commits to stack
  for instruction in "${BRANCHES[@]}"; do
    branch="${instruction%%@*}"
    if ! git rev-parse --verify $branch &> /dev/null; then
      if ! git rev-parse --verify origin/$branch &> /dev/null; then
        echo "Both $branch and origin/$branch do not exist!" >&2
        exit 1
      else
        git branch --track $branch origin/$branch
      fi
    fi
    if [[ -n ${HEADS[$branch]+x} ]]; then
      echo "$branch appears more than once in in \$BRANCHES" >&2
      exit 1
    else
      HEADS["$instruction"]="$(git rev-parse $branch)"
    fi
  done

  fault=0
  for root in "${TARGETS[@]}"; do
    if ! git rev-parse --verify relocatable-base-$root &> /dev/null; then
      if ! git rev-parse --verify origin/relocatable-base-$root &> /dev/null; then
        echo "Target $root not found" >&2
        fault=1
        continue
      else
        git branch relocatable-base-$root origin/relocatable-base-$root
      fi
    fi
    HEADS["relocatable-base-$root"]="$(git rev-parse relocatable-base-$root)"
  done
  if ((fault)); then
    exit 1
  fi

  for instruction in "${BRANCHES[@]}" "${TARGETS[@]}"; do
    if [[ -z ${HEADS[$instruction]} ]]; then
      echo "relocatable-base-$instruction ${HEADS[relocatable-base-$instruction]}"
    else
      echo "$instruction ${HEADS[$instruction]}"
    fi
  done > ../branches

else
  while read -r branch head; do
    if [[ $branch = ${branch#relocatable-base-} ]]; then
      BRANCHES+=($branch)
    else
      TARGETS+=(${branch#relocatable-base-})
    fi
    HEADS[$branch]=$head
  done < <(eval "$lock")
fi

COMMANDS=()
COMMITS=()
WORKING=()
if [[ ! -e $state_file ]]; then
  if [[ -n "$(git status --porcelain)" ]]; then
    echo 'The working tree is not clean' >&2
    exit 1
  fi

  if [[ -e "$(git rev-parse --git-dir)/REBASE_HEAD" ]]; then
    echo 'A rebase appears to be in progress?' >&2
    exit 1
  elif [[ -e "$(git rev-parse --git-dir)/CHERRY_PICK_HEAD" ]]; then
    echo 'A cherry-pick appears to be in progress' >&2
    exit 1
  elif [[ -e "$(git rev-parse --git-dir)/MERGE_HEAD" ]]; then
    echo 'A merge appears to be in progress' >&2
    exit 1
  fi

  git clean -dfX &> /dev/null

  # Calculate the menu. First, determine the initial commit list from the
  # branches.
  for entry in "${BRANCHES[@]}"; do
    upstream="${entry#*@}"
    if [[ $upstream = $entry ]]; then
      upstream='trunk'
    fi
    branch="${entry%%@*}"
    if [[ $upstream =~ ^fixup(~[0-9])?$ ]]; then
      count="${upstream#fixup~}"
      if [[ $count = $upstream ]]; then
        count=0
      fi
      commit="$(git log --format=%h -n 1 "${HEADS[$entry]}")"
      COMMITS+=("adjust $count $entry $commit")
    elif [[ $upstream =~ @fixup$ ]]; then
      upstream="${upstream%@fixup}"
      cmd="$branch"
      count=-1
      while read -r entry; do
        commit="${entry%% *}"
        if [[ $count -eq -1 && ${entry#* } = 'Basis' ]]; then
          continue
        fi
        cmd="$cmd $commit"
        ((count++))
      done < <(git log upstream/$upstream..${HEADS[$entry]} --format="%h %s" --reverse)
      COMMITS+=("adjust $count $cmd")
    else
      while read -r entry; do
        commit="${entry%% *}"
        bootstrap=0
        diffs=0
        while read -r path; do
          case "$path" in
            boot/ocaml*) bootstrap=1;;
            *) diffs=1;;
          esac
        done < <(git diff-tree --no-commit-id --name-only -r "$commit")
        if [[ $bootstrap -eq 1 ]]; then
          if [[ $diffs -eq 0 ]]; then
            COMMITS+=("bootstrap $commit")
          else
            COMMITS+=("coreboot $commit")
          fi
        else
          COMMITS+=("pick $commit")
        fi
      done < <(git log upstream/$upstream..${HEADS[$entry]} --format="%h %s" --reverse)
    fi
  done

  # Now generate commands for each target branch
  for root in "${TARGETS[@]}"; do
    COMMANDS+=("branch relocatable-base-$root")
  done
else
  if [[ -n "$(git ls-files --exclude-standard --others)" ]]; then
    echo 'Untracked files in the working directory' >&2
    exit 1
  elif [[ -n "$(git diff --stat)" ]]; then
    echo 'Unstaged changes in the working directory' >&2
    exit 1
  fi

  # Load the stack state
  phase=0
  while read -r line; do
    case ${line%% *} in
      pick|bootstrap|coreboot|fixup|adjust|next)
        if ((phase)); then
          WORKING+=("$line")
        else
          COMMITS+=("$line")
        fi;;
      commit)
        COMMANDS+=("$line")
        phase=1;;
      branch)
        COMMANDS+=("$line");;
      target)
        target="${line#* }";;
      lock)
        echo "${line#* }" >> ../.stack-branches;;
      *)
        echo "Unrecognised command: $line" >&2
        phase=2;;
    esac
  done < <(cat "$state_file")

  if [[ $phase -gt 1 ]]; then
    exit 1
  fi

  if diff -q ../branches ../.stack-branches > /dev/null ; then
    rm ../.stack-branches
  else
    echo "Branches appear to have been altered:"
    diff ../.stack-branches ../branches
    exit 1
  fi

  rm "$state_file"
fi

rm -f "$lock_index"
if [[ -e ../branches ]]; then
  rm -f branches
  mv ../branches .
  GIT_INDEX_FILE="$lock_index" git add -f branches
  rm branches
fi

function abort
{
  echo "Branch: $branch for $target"
  echo "  $action"
  for commit in "${COMMITS[@]}"; do
    echo "$commit"
  done > "$state_file"
  echo "target $target" >> "$state_file"
  echo "commit $instr" >> "$state_file"
  for instruction in "${BRANCHES[@]}" "${TARGETS[@]}"; do
    if [[ -z ${HEADS[$instruction]} ]]; then
      echo "lock relocatable-base-$instruction ${HEADS[relocatable-base-$instruction]}" >> "$state_file"
    else
      echo "lock $instruction ${HEADS[$instruction]}" >> "$state_file"
    fi
  done
  aborting=1
}

function merge-base
{
  local base="$(git merge-base "$1" "$2")"
  # There's an error in the branching history for 4.13, possibly caused by PRs
  # merged shortly after it was branched. The effect is that there are two
  # "last commit before branching 4.13" commits in the history which causes the
  # common parent dd7927 to be selected. We manually amend this to 4.13's
  # merge-base.
  if [[ $base = 'dd7927e156b7cb2f9cb73d2d54a15a9c81921392' ]]; then
    base='621753f3eec9de91495a25723de00cef33a9e35a'
  fi
  echo "$base"
}

# Return status 0 only if the commit specified by $1 is based on a branch which
# is newer than the commit specified by $2 (i.e. cherry-picking $1 onto $2 would
# be a back-port, not a revert)
function is-backport
{
  local commit="$1"
  local target="$2"
  # The multicore merge history (from #10831) causes issues for `git merge-base`
  # $pre_10831 is the last commit on trunk before #10831 was merged. If that
  # commit is _not_ an ancestor of $target, then we use that instead of the tip
  # of trunk to work out the merge-base, as this avoids the complicated rebase
  # and merge history in #10831.
  pre_10831='263a2a429c'
  if git merge-base --is-ancestor $pre_10831 "$target"; then
    trunk='upstream/trunk'
  else
    trunk=$pre_10831
  fi
  target_sha="$(git rev-list -n 1 "$target")"
  target_mergebase="$(merge-base "$target" $trunk)"
  mergebase="$(merge-base "$commit" "$target")"
  if [[ $mergebase = $target_sha ]]; then
    # Commit is based on target!
    return
  elif [[ $mergebase = $target_mergebase ]]; then
    # The common point between $commit and $target is $target's merge-base with
    # trunk. That means $commit is newer, as otherwise the common point would
    # be the merge-base of $commit and trunk.
    return
  fi

  # This isn't a back-port
  return 1
}

function reset-committer
{
  if ! git rebase --committer-date-is-author-date HEAD~1 &> /dev/null; then
    git rebase --committer-date-is-author-date HEAD~1
    echo "Resetting the committer date on the last commit has failed" >&2
    exit 1
  fi
}

function rebase
{
  while [[ ${#WORKING[@]} -gt 0 ]]; do
    instr="${WORKING[0]}"
    WORKING=("${WORKING[@]:1}")
    sha="${instr#* }"
    verb="${instr%% *}"
    case $verb in
      next)
        COMMITS+=("$sha");;
      pick|fixup)
        if [[ $verb = 'fixup' ]]; then
          echo "fixup $sha on $target ($(git log -n 1 --format=%s $sha))"
          msg="$(git rev-parse --short HEAD)"
          amend='--amend'
          next=''
        else
          echo "cherry-pick $sha to $target ($(git log -n 1 --format=%s $sha))"
          msg="$sha"
          amend=''
          next='pick $head'
        fi
        if cherry-pick "$sha"; then
          commit "$msg" "$next" "$instr" "$amend"
        fi;;
      bootstrap)
        echo "Bootstrap $target ($sha) on $(git rev-parse --short HEAD)"
        cached="$(git reflog --format='%h %p' | grep " $(git rev-parse --short HEAD)$" | head -n 1 | cut -f1 -d' ')"
        if [[ -n $cached ]] && git diff-tree --no-commit-id --name-only -r "$cached" | grep -Fq 'boot/ocaml'; then
          echo "Re-using previous bootstrap computation from $cached"
          git merge --ff-only $cached &> /dev/null
          COMMITS+=("bootstrap $cached")
        else
          BOOTSTRAPS+=("Bootstrap $target ($sha) on $(git rev-parse --short HEAD)")
          echo "Bootstrapping..."
          if ! ./configure --disable-native-compiler --disable-ocamldoc --disable-ocamltest --disable-debugger > _log 2>&1; then
            cat _log
            rm _log
            abort
            echo "configure failed: either fix or erase $state_file"
          elif ! make -j coldstart > _log 2>&1; then
            cat _log
            rm _log
            abort
            echo "make coldstart failed: either fix or erase $state_file"
            echo 'Do _not_ bootstrap'
          elif ! make -j coreall > _log 2>&1; then
            cat _log
            rm _log
            abort
            echo "make coreall failed: either fix or erase $state_file"
            echo 'Do _not_ bootstrap'
          elif ! make -j bootstrap > _log 2>&1; then
            cat _log
            rm _log
            abort
            git reset -- boot/ocaml* &> /dev/null
            git checkout -- boot/ocaml* &> /dev/null
            echo "make bootstrap failed: either fix or erase $state_file"
            echo 'Do _not_ bootstrap'
          else
            rm _log
            git clean -dfX &> /dev/null
            # OCaml 4.06 and earlier
            if [[ -e boot/ocamldep ]]; then
              git add -- boot/ocamldep
            fi
            git add -- boot/ocamlc boot/ocamllex
            commit "$sha" 'bootstrap $head' "$instr"
          fi
        fi;;
      coreboot)
        coreboot="Coreboot $target ($sha) on $(git rev-parse --short HEAD)"
        echo "$coreboot"
        if cherry-pick "$sha" 'boot/ocaml*' 'Do _not_ bootstrap'; then
          next="${WORKING[0]}"
          if [[ ${next%% *} = 'fixup' ]]; then
            echo "Skipping coreboot - next command is a fixup"
            if ! git commit --reuse-message="$sha" &> _log; then
              cat _log
              rm _log
              abort
              echo "Commit failed - please fix and re-run $0"
              echo 'Do _not_ bootstrap'
            else
              rm _log
              reset-committer
              COMMITS+=("coreboot $(git rev-parse --short HEAD)")
            fi
          else
            coreboot "$sha"
          fi
        fi;;
      *)
        echo "Internal error: unrecognised command $instr" >&2
        exit 1;;
    esac
    if ((aborting)); then
      for instr in "${WORKING[@]}"; do
        echo "$instr" >> "$state_file"
      done
      WORKING=()
    fi
  done
}

function reconfigure
{
  reconfigure=0
  while read -r item; do
    case $item in
      configure|configure.ac|aclocal.m4|build-aux/*)
        reconfigure=1;;
    esac
  done < <(git diff --name-only --cached)
  if ((reconfigure)); then
    echo "configure.ac has been changed - regenerating configure"
    if [[ -e tools/autogen ]]; then
      autogen=tools/autogen
    else
      autogen=./autogen
    fi
    rm -f configure
    if [[ $(sed -ne 's/^AC_PREREQ(\[\(.*\)\])$/\1/p' configure.ac) =~ ^(2.69)?$ ]]; then
      if grep -q '^autoconf ' $autogen; then
        restore="sed -i -e 's/^\${1-autoconf}/autoconf/' $autogen"
        sed -i -e 's/^autoconf/${1-autoconf}/' $autogen
      elif grep -q '[^$]autoconf -' $autogen; then
        restore="sed -i -e 's/\${1-autoconf}/autoconf/' $autogen"
        sed -i -e 's/autoconf -/${1-autoconf} -/' $autogen
      else
        restore=''
      fi
      autogen="$autogen autoconf2.69"
    fi
    if $autogen; then
      eval $restore
      git add -- configure
    else
      eval $restore
      abort
      echo "Regenerating configure failed - please fix and re-run $0"
      return 1
    fi
  fi
}

function cherry-pick
{
  git cherry-pick --no-commit "$1" >& /dev/null
  git reset -- Changes $2 &> /dev/null
  git checkout -- Changes $2 &> /dev/null
  if reconfigure; then
    while read -r status; do
      case ${status:0:2} in
        DU)
          git reset -- "${status:3}" &> /dev/null
          TO_DELETE+=("${status:3}");;
        UU|AA)
          if ! grep -q '^<<<<<' "${status:3}" ; then
            git add -- "${status:3}"
          else
            git reset -- "${status:3}" &>/dev/null
          fi;;
      esac
    done < <(git status --porcelain)

    if [[ -n $(git diff --stat) ]]; then
      abort
      git status
      echo
      echo "Please resolve changes, add to the index and re-run $0"
      if [[ -n $3 ]]; then
        echo "$3"
      fi
      return 1
    else
      return 0
    fi
  else
    return 1
  fi
}

function coreboot
{
  head_sha="$(git rev-parse --short HEAD)"
  # Check the cache
  if ! git commit --reuse-message="$1" &> _log; then
    cat _log
    rm _log
    abort
    echo "Commit failed - please fix and re-run $0"
  else
    rm _log
    reset-committer
    code_sha="$(git rev-parse --short HEAD)"
    cached="$(git reflog --format='%h %p' | grep " ${code_sha}\$" | head -n 1 | cut -f1 -d' ')"
    if [[ -n $cached ]] && git diff-tree --no-commit-id --name-only -r "$cached" | grep -Fq 'boot/ocaml'; then
      # This code commit has a bootstrap parent - so we can search for a unified commit
      combined=''
      while read -r commit; do
        if git diff --quiet $cached $commit; then
          combined="$commit"
          break;
        fi
      done < <(git reflog --format='%h %p' | grep " ${head_sha}\$" | cut -f1 -d' ' | sort | uniq)
      if [[ -n $combined ]] && git diff-tree --no-commit-id --name-only -r "$combined" | grep -Fq 'boot/ocaml'; then
        echo "Re-using previous coreboot computation from $combined"
        git reset --hard $combined &> /dev/null
        if [[ $(git log -1 --format='%cn <%ce> on %cd') != $(git log -1 --format='%an <%ae> on %ad') ]]; then
          reset-committer
          new="$(git rev-parse --short HEAD)"
          echo "Reset committer information on $combined to give $new"
          combined="$new"
        fi
        COMMITS+=("coreboot $combined")
        return
      fi
    fi
    git reset --hard $head_sha &> /dev/null
    if ! ./configure --disable-native-compiler --disable-ocamldoc --disable-ocamltest --disable-debugger > _log 2>&1; then
      cat _log
      rm _log
      abort
      echo "configure failed: either fix or erase $state_file"
      return
    fi
    BOOTSTRAPS+=("$coreboot")
    echo 'Warming up...'
    if ! make -j coldstart > _log 2>&1; then
      cat _log
      rm _log
      abort
      echo "make coldstart failed: either fix or erase $state_file"
      return
    fi
    echo 'Building...'
    if ! git merge --ff-only $code_sha &> /dev/null || ! { ./config.status ; make -j coreall ; } > _log 2>&1 ; then
      cat _log
      rm _log
      git reset --hard $head_sha &> /dev/null
      git cherry-pick --no-commit $code_sha &> /dev/null
      abort
      echo "make coreall failed: either fix or erase $state_file"
      echo 'Do _not_ bootstrap'
      return
    fi
    echo 'Bootstrapping...'
    if ! make -j bootstrap > _log 2>&1; then
      cat _log
      rm _log
      git reset --hard $head_sha &> /dev/null
      git cherry-pick --no-commit $code_sha &> /dev/null
      abort
      echo "make bootstrap failed: either fix or erase $state_file"
      echo 'Do _not_ bootstrap'
    else
      rm _log
      git clean -dfX &> /dev/null
      # OCaml 4.06 and earlier
      if [[ -e boot/ocamldep ]]; then
        git add -- boot/ocamldep
      fi
      git add -- boot/ocamlc boot/ocamllex
      if ! git commit -m 'Bootstrap' &> _log; then
        cat _log
        rm _log
        abort
        echo "Commit failed - please fix and re-run $0"
      else
        rm -f _log
        reset-committer
        boot_sha="$(git rev-parse --short HEAD)"
        git reset --hard HEAD~1 &> /dev/null
        git cherry-pick --no-commit $boot_sha &> /dev/null
        git commit --reuse-message="$1" --amend &> /dev/null
        reset-committer
        head="$(git rev-parse --short HEAD)"
        COMMITS+=("coreboot $head")
      fi
    fi
  fi
}

TO_DELETE=()
function commit
{
  for file in "${TO_DELETE[@]}"; do
    rm -f "$file"
  done
  TO_DELETE=()
  if [[ -z "$(git status --porcelain)" ]]; then
    echo "Commit $1 skipped for $target (empty)"
    head="$(git rev-parse --short HEAD)"
  else
    if ! git commit --reuse-message="$1" $4 &> _log; then
      cat _log
      rm _log
      abort
      echo "Commit failed - please fix and re-run $0"
      return
    fi
    rm -f _log
    reset-committer
    head="$(git rev-parse --short HEAD)"
    #echo "Committed HEAD $head"
    if [[ -n $2 ]]; then
      eval "com=\"$2\""
      COMMITS+=("$com")
    else
      previous="${COMMITS[-1]}"
      COMMITS[-1]="${previous%% *} $head"
    fi
  fi
  if [[ -z $2 ]]; then
    previous="${COMMITS[-1]}"
    if [[ ${previous%% *} = 'coreboot' ]]; then
      echo "Repeating the previous coreboot"
      # It's slightly simpler just repeat the coreboot commit rather than
      # threading this through the entire fixup logic that it needs to
      # coldstart with HEAD~1. The changes would either need stashing or
      # committing in stages, etc. which muddles the error code.
      # Throw this commit away
      git reset --hard HEAD~1 &> /dev/null
      # Remove the previous coreboot from COMMITS
      COMMITS=("${COMMITS[@]:0:$((${#COMMITS[@]} - 1))}")
      # Add this commit to be coreboot'd now
      WORKING=("coreboot $head" "${WORKING[@]}")
    fi
  fi
}

# Useful loop for identifying branches needing rebasing
#our_base="$(git rev-parse relocatable-base-trunk)"
#our_base='d98fd806573088994b0ab60de032d7d54221488f'
#for entry in "${BRANCHES[@]}"; do
#  base="$(merge-base ${entry%%@*} upstream/trunk)"
#  if [[ $base = $our_base ]]; then
#    echo "$entry: $base"
#  fi
#done
#exit 0

BOOTSTRAP=()
aborting=0
while [[ ${#COMMANDS[@]} -gt 0 ]]; do
  instr="${COMMANDS[0]}"
  COMMANDS=("${COMMANDS[@]:1}")
  arg="${instr#* }"
  case ${instr%% *} in
    commit)
      git clean -dfX &> /dev/null
      verb="${arg% *}"
      instr="$arg"
      if [[ $verb = 'coreboot' ]]; then
        coreboot "${arg#* }"
      else
        if [[ $verb = 'fixup' ]]; then
          msg="$(git rev-parse --short HEAD)"
          next=''
          amend='--amend'
        else
          msg="${arg#* }"
          next="$verb \$head"
          amend=''
        fi
        if reconfigure; then
          commit "$msg" "$next" "$arg" "$amend"
          if ((!aborting)); then
            rebase
          fi
        fi
      fi;;
    branch)
      target_branch="backport-${arg#relocatable-base-}"
      echo "Creating branch $target_branch"
      target="$arg"
      WORKING=()
      for cmd in "${COMMITS[@]}"; do
        verb="${cmd%% *}"
        sha="${cmd#* }"
        case "$verb" in
          pick|bootstrap|coreboot)
            if ! is-backport "$sha" "${HEADS[$target]}"; then
              echo "Skipping $sha as it's older than $target ($(git log -n 1 --format=%s $sha))"
              WORKING+=("next $cmd")
            else
              WORKING+=("$cmd")
            fi;;
          adjust)
            # INSTR[0] = adjust; INSTR[1] = count; INSTR[2] = description; INSTR[@]:3 = commits
            INSTR=($cmd)
            if ! is-backport "${INSTR[3]}" "${HEADS[$target]}"; then
              WORKING+=("next $cmd")
              echo "Skipping ${INSTR[2]} as it's older than $target"
            else
              count="${INSTR[1]}"
              if [[ $count -eq 0 ]]; then
                POPPED=()
              else
                i=0
                while [[ $count -gt 0 ]]; do
                  ((i++))
                  element="${WORKING[-$i]}"
                  case "${element%% *}" in
                    fixup|next) ;;
                    *) ((count--));
                  esac
                done
                POPPED=("${WORKING[@]: -$i}")
                WORKING=("${WORKING[@]:0:$((${#WORKING[@]} - $i))}")
              fi
              INSTR=("${INSTR[@]:3}")
              while [[ ${#INSTR[@]} -gt 0 ]]; do
                sha="${INSTR[0]}"
                INSTR=("${INSTR[@]:1}")
                WORKING+=("fixup $sha")
                loop=1
                if [[ ${#POPPED[@]} -gt 0 && $loop -eq 1 ]]; then
                  elt="${POPPED[0]}"
                  WORKING+=("$elt")
                  POPPED=("${POPPED[@]:1}")
                  case "${elt%% *}" in
                    fixup|next) ;;
                    *) loop=0;;
                  esac
                fi
              done
            fi;;
          *)
            echo "Internal error: unrecognised command $cmd" >&2
            exit 1;;
          esac
      done
      COMMITS=()
      git checkout -B "$target_branch" "${HEADS[$arg]}" &> /dev/null
      rebase;;
    *)
      echo "Internal error: unrecognised command $instr" >&2
      exit 1;;
  esac
  if ((aborting)); then
    for instr in "${COMMANDS[@]}"; do
      echo "$instr" >> "$state_file"
    done
    COMMANDS=()
  fi
done

cd ..
if ((!aborting)); then
  git submodule update
  git -C "$dir" clean -dfX &> /dev/null
fi

if [[ ${#BOOTSTRAPS[@]} -gt 0 ]]; then
  echo
  echo Bootstrap summary:
  for msg in "${BOOTSTRAPS[@]}"; do
    echo " - $msg"
  done
fi

if ((aborting)); then
  exit 2
fi

declare -A BACKPORTS
if [[ -n $backports ]]; then
  # Load from the file
  while read -r root sha; do
    BACKPORTS[$root]="$sha"
  done < <(git -C "$dir" show "$backports:backports")
else
  # Load from origin
  for root in "${TARGETS[@]}"; do
    BACKPORTS[backport-$root]="$(git -C "$dir" rev-parse origin/backport-$root)"
  done
fi

return_to="$(git -C "$dir" rev-parse HEAD)"
echo "Backport summary (first sha is just built; second sha is expected)"
echo -e " - Identical shas \e[90mgreyed out\e[0m;"
echo -e " - Differ only by commit date (old stack bug) \e[32min green\e[0m;"
echo -e " - Final tree identical but commit sequence differs \e[33min yellow\e[0m;"
echo -e " - Trees differ \e[31min red\e[0m with differences shown"
for root in "${TARGETS[@]}"; do
  calculated_sha="$(git -C "$dir" rev-parse backport-$root)"
  recorded_sha="${BACKPORTS[backport-$root]}"
  if [[ $calculated_sha = $recorded_sha ]]; then
    echo -e "backport-$root: \e[90m$calculated_sha $recorded_sha\e[0m"
  elif ! git -C "$dir" diff --exit-code --quiet $recorded_sha $calculated_sha; then
    echo -e "backport-$root: $calculated_sha \e[31m$recorded_sha\e[0m"
    git --no-pager -C "$dir" diff --stat $recorded_sha $calculated_sha
  else
    git -C "$dir" checkout -qB stack-checking-for-committer $recorded_sha
    git -C "$dir" rebase --committer-date-is-author-date ${HEADS[relocatable-base-$root]} &> /dev/null
    cleaned_sha="$(git -C "$dir" rev-parse HEAD)"
    git -C "$dir" checkout -q $return_to
    git -C "$dir" branch -qD stack-checking-for-committer
    if [[ $cleaned_sha = $calculated_sha ]]; then
      echo -e "backport-$root: $calculated_sha \e[32m$recorded_sha\e[0m"
    else
      echo -e "backport-$root: $calculated_sha \e[33m$recorded_sha\e[0m"
    fi
  fi
done

if [[ ! -e $lock_index ]]; then
  exit 0
fi

cd "$dir"

GIT_INDEX_FILE="$lock_index" git --work-tree=../.git/modules/ocaml add \
  $(cd ../.git/modules/ocaml ; \
    find rr-cache -type f -newermt "$start_time" -name postimage\*) \
  $(cd ../.git/modules/ocaml ;
    find rr-cache -type f -newermt "$start_time" -name postimage\* | sed -e 's/postimage/preimage/')

for root in "${TARGETS[@]}"; do
  echo "backport-$root $(git rev-parse backport-$root)"
done > backports
GIT_INDEX_FILE="$lock_index" git add backports
rm backports

lock_tree_sha="$(GIT_INDEX_FILE="$lock_index" git write-tree)"
locks_head="$(git rev-parse relocatable-locks)"
found_lock=''
while read -r commit tree; do
  if [[ $tree = $lock_tree_sha ]]; then
    found_lock="$commit"
    break
  fi
done < <(git log relocatable-locks --format="%h %T")

if [[ -z $found_lock ]]; then
  parents=()
  for instruction in "${BRANCHES[@]}" "${TARGETS[@]}"; do
    if [[ -z ${HEADS[$instruction]} ]]; then
      parents+=(-p ${HEADS[relocatable-base-$instruction]})
    else
      parents+=(-p ${HEADS[$instruction]})
    fi
  done
  for root in "${TARGETS[@]}"; do
    parents+=(-p $(git rev-parse backport-$root))
  done
  lock_tree_commit="$(git commit-tree -m Lock -p "$locks_head" "${parents[@]}" "$lock_tree_sha")"
  git branch -f relocatable-locks "$lock_tree_commit"
  echo "Added $lock_tree_commit to relocatable-locks"
else
  echo "Lock $lock_tree_sha already present in relocatable-locks @ $found_lock"
fi

cd ..
